import { GeneratedDoc } from '../types';

export const downloadFile = (filename: string, content: string, contentType: string) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const generateMarkdown = (repoName: string, docs: GeneratedDoc[]): string => {
  const timestamp = new Date().toLocaleDateString();
  
  let md = `# ${repoName} API Documentation\n`;
  md += `> Generated by AutoDoc AI on ${timestamp}\n\n`;
  
  md += `## Table of Contents\n`;
  docs.forEach(doc => {
    if (doc.endpoints.length > 0) {
      doc.endpoints.forEach(ep => {
        const anchor = `${ep.method.toLowerCase()}-${ep.path.replace(/[^a-z0-9]/gi, '').toLowerCase()}`;
        md += `- [${ep.method} ${ep.path}](#${anchor})\n`;
      });
    }
  });
  md += `\n---\n`;

  docs.forEach(doc => {
    if (doc.endpoints.length === 0) return;

    md += `\n## File: \`${doc.fileName}\`\n`;
    md += `${doc.overview}\n\n`;

    doc.endpoints.forEach(ep => {
      md += `### ${ep.method} ${ep.path}\n`;
      md += `**Summary**: ${ep.summary}\n\n`;
      
      if (ep.parameters.length > 0) {
        md += `#### Parameters\n`;
        md += `| Name | Type | Required | Description |\n`;
        md += `|------|------|----------|-------------|\n`;
        ep.parameters.forEach(p => {
          md += `| \`${p.name}\` | ${p.type} | ${p.required ? 'Yes' : 'No'} | ${p.description} |\n`;
        });
        md += `\n`;
      }

      md += `#### Response\n`;
      md += `- **Type**: \`${ep.response.type}\`\n`;
      md += `- **Description**: ${ep.response.description}\n`;
      
      md += `\n---\n`;
    });
  });

  return md;
};

export const generateHtmlReport = (repoName: string, docs: GeneratedDoc[]): string => {
  const allEndpoints = docs.flatMap(d => d.endpoints.map(ep => ({...ep, fileName: d.fileName})));
  const timestamp = new Date().toLocaleDateString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${repoName} - API Docs</title>
    <style>
        :root { --bg: #0f172a; --card: #1e293b; --text: #e2e8f0; --brand: #3b82f6; --border: #334155; }
        body { font-family: -apple-system, system-ui, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; line-height: 1.6; }
        .container { max-width: 1000px; margin: 0 auto; }
        h1 { color: #fff; border-bottom: 1px solid var(--border); padding-bottom: 1rem; }
        .badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }
        .GET { background: rgba(59, 130, 246, 0.2); color: #60a5fa; }
        .POST { background: rgba(34, 197, 94, 0.2); color: #4ade80; }
        .PUT { background: rgba(234, 179, 8, 0.2); color: #facc15; }
        .DELETE { background: rgba(239, 68, 68, 0.2); color: #f87171; }
        .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; margin-bottom: 2rem; overflow: hidden; }
        .card-header { padding: 1rem; background: rgba(255,255,255,0.05); border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; }
        .path { font-family: monospace; font-size: 1.1rem; margin-left: 1rem; }
        .card-body { padding: 1.5rem; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }
        th { text-align: left; border-bottom: 1px solid var(--border); padding: 0.5rem; color: #94a3b8; }
        td { border-bottom: 1px solid var(--border); padding: 0.5rem; }
        .meta { font-size: 0.8rem; color: #94a3b8; margin-top: 2rem; text-align: center; }
        .file-tag { font-size: 0.75rem; background: #334155; padding: 2px 6px; border-radius: 4px; color: #cbd5e1; }
    </style>
</head>
<body>
    <div class="container">
        <h1>${repoName} API Documentation</h1>
        <p>Generated automatically on ${timestamp}</p>

        ${allEndpoints.length === 0 ? '<p>No endpoints detected.</p>' : ''}

        ${allEndpoints.map(ep => `
        <div class="card">
            <div class="card-header">
                <div>
                    <span class="badge ${ep.method}">${ep.method}</span>
                    <span class="path">${ep.path}</span>
                </div>
                <span class="file-tag">${ep.fileName}</span>
            </div>
            <div class="card-body">
                <p>${ep.summary}</p>
                
                ${ep.parameters.length > 0 ? `
                <h4>Parameters</h4>
                <table>
                    <thead><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>
                    <tbody>
                        ${ep.parameters.map(p => `
                        <tr>
                            <td><code>${p.name}</code></td>
                            <td>${p.type}</td>
                            <td>${p.required ? 'Yes' : '-'}</td>
                            <td>${p.description}</td>
                        </tr>
                        `).join('')}
                    </tbody>
                </table>
                ` : ''}

                <h4>Returns</h4>
                <div style="background: rgba(0,0,0,0.2); padding: 1rem; border-radius: 4px; font-family: monospace;">
                    <span style="color: #c084fc">${ep.response.type}</span> 
                    <span style="color: #64748b">// ${ep.response.description}</span>
                </div>
            </div>
        </div>
        `).join('')}

        <div class="meta">
            Generated with AutoDoc AI
        </div>
    </div>
</body>
</html>`;
};